name: Build LKM for KernelSU
on:
  push:
    branches: ["main", "ci", "checkci"]
    paths:
      - ".github/workflows/build-lkm.yml"
      - 'kernel/**'
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/build-lkm.yml"
      - 'kernel/**'
  workflow_call:
  workflow_dispatch:
jobs:
  build-lkm:
    strategy:
      matrix:
        include:
          - version: "android12-5.10"
            sub_level: 218
            os_patch_level: 2024-08
          - version: "android13-5.10"
            sub_level: 218
            os_patch_level: 2024-08
          - version: "android13-5.15"
            sub_level: 151
            os_patch_level: 2024-08
          - version: "android14-5.15"
            sub_level: 158
            os_patch_level: 2024-08
          - version: "android14-6.1"
            sub_level: 90
            os_patch_level: 2024-08
          - version: "android15-6.6"
            sub_level: 30
            os_patch_level: 2024-08
    uses: ./.github/workflows/gki-kernel.yml
    with:
      version: ${{ matrix.version }}
      version_name: ${{ matrix.version }}.${{ matrix.sub_level }}
      tag: ${{ matrix.version }}-${{ matrix.os_patch_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      build_lkm: true

  
  push-to-branch:
    needs: [build-lkm]
    runs-on: ubuntu-latest
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          path: bin/
          merge-multiple: true
      - name: Push to branch LKM
        run: |
          cd bin
          git init
          git remote add origin https://${{ github.actor }}:${{ secrets.TOKEN }}@github.com/${{ github.repository }}
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add *-lkm
          git commit -m "Upload LKM"
          git push --force --set-upstream origin lkm
